apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-website-deployment
  labels:
    app: car-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-website
  template:
    metadata:
      labels:
        app: car-website
    spec:
      containers:
      - name: car-website-container
        # Jenkinsfile ki sed command is 'latest' ko build number se replace kar degi
        image: amarjeet001/car-website:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
